import bcrypt from "bcryptjs";import crypto from "crypto";import{connectDatabase}from "./mongo";import{User,Affiliate,Category,Product,PaymentMethod,SiteSettings,Banner,PromoVideo,PromoImage,InventoryTransaction,Review}from "../models";import {env} from "../config/env";
(async()=>{if(env.NODE_ENV==="production")throw new Error("Seed is disabled in production");await connectDatabase();await Promise.all([User.deleteMany({}),Affiliate.deleteMany({}),Category.deleteMany({}),Product.deleteMany({}),PaymentMethod.deleteMany({}),SiteSettings.deleteMany({}),Banner.deleteMany({}),PromoVideo.deleteMany({}),PromoImage.deleteMany({}),Review.deleteMany({})]);
const names=["Beauty & Personal Care","Perfumes","Watches","Women's Fashion"];const cats=await Category.insertMany(names.map((name,i)=>({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),active:true,sortOrder:i,description:`Seed category for ${name}`})));
const img=[
"https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
"https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
"https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80",
"https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=80"];
const catalog=[
["Face Scrub","Skin Care Cream","Hydrating Moisturizer","Gentle Face Wash","Vitamin C Serum","Lip Care Balm","Glow Essentials"],
["Men's Perfume","Women's Perfume","Premium Fragrance","Oud Collection","Floral Mist","Amber Eau de Parfum","Everyday Cologne"],
["Men's Watch","Women's Watch","Fashion Watch","Classic Steel Watch","Minimalist Watch","Leather Strap Watch","Premium Chronograph"],
["Embroidered Suit","Summer Dress","Printed Dupatta","Silk Stole","Lawn Suit","Party Dress","Chiffon Stole"]
];
for(let i=0;i<cats.length;i++)for(let n=1;n<=7;n++){
 const name=catalog[i][n-1];const hasVariants=i>=2&&n<=4;
 const original=[1499,3499,7999,4499][i]+n*250;const sale=Math.round(original*(n<=3?.8:.9));
 const variants=hasVariants?[{sku:`NC-${i+1}-${n}-S`,name:`${name} Small`,attributes:{color:"Black",size:"S"},color:"Black",size:"S",price:sale,compareAtPrice:original,stock:8,active:true,images:[img[i]],weight:0.5,commissionType:"percentage",commissionValue:5},
 {sku:`NC-${i+1}-${n}-M`,name:`${name} Medium`,attributes:{color:"Black",size:"M"},color:"Black",size:"M",price:sale,compareAtPrice:original,stock:8,active:true,images:[img[i]],weight:0.6,commissionType:"percentage",commissionValue:5}]:[];
 const limited=n===7;
 const product=await Product.create({name,slug:`demo-${i+1}-${n}-${name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`,sku:`NC-DEMO-${i+1}-${n}`,brand:["DermaCare","Nova Scents","TimeCraft","Libaas Studio"][i],category:cats[i]._id,description:`Professional demo product for NovaCart development. Replace this description and media from Admin when your real catalog is ready.`,shortDescription:`Demo ${name}`,originalPrice:original,salePrice:sale,discount:Math.round((1-sale/original)*100),discountType:"percentage",discountValue:Math.round((1-sale/original)*100),discountPercentage:Math.round((1-sale/original)*100),limitedTimeOffer:limited,offerStartDate:limited?new Date(Date.now()-86400000):undefined,offerEndDate:limited?new Date(Date.now()+7*86400000):undefined,stock:hasVariants?0:20+n,variants,images:[img[i],img[(i+1)%img.length]],video:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",videoThumbnail:img[i],colors:["Black","White","Rose"],sizes:["S","M","L"],weight:0.5+n/10,gender:i===3?"Female":(n%3===0?"Unisex":"Male"),availability:true,featured:n<=2,newArrival:n>=5,bestSeller:n<=3,limitedStock:limited,tags:["demo","replace-me"],commissionType:"percentage",commissionValue:5,active:true});
 if(hasVariants){for(const v of product.variants)await InventoryTransaction.create({product:product._id,variantId:v._id,sku:v.sku,change:v.stock,balanceAfter:v.stock,type:"INITIAL_STOCK",note:"Demo inventory"});}
 else await InventoryTransaction.create({product:product._id,sku:product.sku,change:product.stock,balanceAfter:product.stock,type:"INITIAL_STOCK",note:"Demo inventory"});
}
async function addUser(name:string,email:string,role:any){const c="AFF-"+crypto.randomBytes(5).toString("hex").toUpperCase();const u=await User.create({name,email,passwordHash:await bcrypt.hash(role==="admin"?"Admin123!ChangeMe":"Customer123!ChangeMe",12),role,affiliateCode:c,emailVerified:true});await Affiliate.create({user:u._id,code:c,active:true});}
await addUser("NovaCart Admin","admin@novacart.local","admin");await addUser("Demo Customer","customer@novacart.local","customer");const demoCustomer:any=await User.findOne({email:"customer@novacart.local"});const demoProducts:any[]=await Product.find().limit(4);if(demoCustomer)await Review.insertMany(demoProducts.map((p:any,i:number)=>({product:p._id,user:demoCustomer._id,rating:5-i%2,title:"Demo review",body:"Demo review for storefront testing.",moderationStatus:"APPROVED",approved:true})));
await PaymentMethod.insertMany([{name:"Easypaisa",type:"WALLET",requiresTransactionId:true,requiresReceipt:false,requiresManualReview:true,active:true,instructions:"Configure your Easypaisa account details in Admin."},{name:"JazzCash",type:"WALLET",requiresTransactionId:true,requiresReceipt:false,requiresManualReview:true,active:true,instructions:"Configure your JazzCash account details in Admin."},{name:"Bank Transfer",type:"BANK_TRANSFER",requiresTransactionId:true,requiresReceipt:true,requiresManualReview:true,active:true,instructions:"Configure your bank account details in Admin."},{name:"Cash on Delivery",type:"COD",requiresTransactionId:false,requiresReceipt:false,requiresManualReview:false,active:true,instructions:"Pay on delivery."}]);;
await SiteSettings.create({storeName:"NovaCart",currency:"PKR",shippingFee:250,freeShippingThreshold:5000,defaultCommission:5,storeStatus:"OPEN",maintenanceMode:false,contact:{email:"support@example.com",phone:"+92 300 0000000"},social:{whatsapp:"https://wa.me/923000000000",messenger:"https://m.me/novacart.demo",telegram:"https://t.me/novacart_demo",tiktok:"https://www.tiktok.com/@novacart.demo"},homepage:{}});await Banner.insertMany([
{title:"New Season Essentials",subtitle:"Beauty, fragrance, watches and fashion delivered across Pakistan.",image:img[3],buttonText:"Shop now",buttonUrl:"/products",active:true,sortOrder:1},
{title:"Fragrance Edit",subtitle:"Discover signature scents at demo prices.",image:img[1],buttonText:"Explore perfumes",buttonUrl:"/products/perfumes",active:true,sortOrder:2},
{title:"Time to Shine",subtitle:"Modern watches for everyday style.",image:img[2],buttonText:"Shop watches",buttonUrl:"/products/watches",active:true,sortOrder:3}]);
await PromoImage.insertMany([
{title:"Beauty picks",description:"Fresh skincare essentials for your daily routine.",image:img[0],buttonText:"Shop beauty",buttonUrl:"/products/beauty-personal-care",active:true,sortOrder:1},
{title:"Signature scents",description:"Find your next everyday fragrance.",image:img[1],buttonText:"Shop perfumes",buttonUrl:"/products/perfumes",active:true,sortOrder:2},
{title:"Style edit",description:"Complete your look with watches and fashion.",image:img[3],buttonText:"Shop fashion",buttonUrl:"/products/womens-fashion",active:true,sortOrder:3}]);
await PromoVideo.create({url:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",thumbnail:img[0],title:"NovaCart demo story",description:"A placeholder promotional video. Replace it from Admin when ready.",active:true,sortOrder:1});console.log("Seed complete. Demo credentials are intended for local development only.");process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
