import mongoose from "mongoose";import crypto from "crypto";import jwt from "jsonwebtoken";
import { Product,Order,SiteSettings,Affiliate,AffiliateClick,Coupon,Cart,PaymentMethod,Notification,User } from "../models";
import { env } from "../config/env";import { roundMoney,percentMoney } from "../utils/money";import { reserveUsage,validate as validateCoupon,ensureUserUsage } from "./coupons.service";
import { adjust as adjustInventory } from "./inventory.service";import {effectivePrice} from "./products.service";
const fail=(message:string,status=400)=>Object.assign(new Error(message),{status});
const orderNo=()=>`ORD-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(5).toString("hex").toUpperCase()}`;
function commissionSnapshot(p:any,v:any,line:number,qty:number,settings:any){const now=new Date();const configured=v?.commissionType&&v.commissionType!=="default"?v.commissionType:(p.commissionType||"default");const activeWindow=(!p.commissionStart||p.commissionStart<=now)&&(!p.commissionEnd||p.commissionEnd>=now);if(configured!=="default"&&!activeWindow)return{type:configured,rate:configured==="percentage"?Number(v?.commissionValue??p.commissionValue??0):undefined,fixedCommissionAmount:configured==="fixed"?Number(v?.commissionValue??p.commissionValue??0):undefined,calculatedAmount:0};const type=configured==="fixed"?"fixed":"percentage";const value=configured!=="default"?Number(v?.commissionValue??p.commissionValue??0):Number(settings?.defaultCommission||0);return type==="fixed"?{type,rate:undefined,fixedCommissionAmount:value,calculatedAmount:roundMoney(value*qty)}:{type,rate:value,fixedCommissionAmount:undefined,calculatedAmount:percentMoney(line,value)};}
function cartVariant(v:any,p:any){if(!p.variants?.length)return null;if(!v?.variantId)throw fail(`Please select a variant for ${p.name}`);const selected=p.variants.id(v.variantId);if(!selected||selected.active===false)throw fail(`Invalid variant for ${p.name}`);return selected;}
export async function createOrder(userId:string,input:any,rawAttribution?:string,idempotencyKey?:string){const idempotencyFingerprint=idempotencyKey?crypto.createHash("sha256").update(JSON.stringify({paymentMethod:input.paymentMethod,address:input.address,couponCode:input.couponCode||null})).digest("hex"):undefined;if(input.couponCode){const c:any=await Coupon.findOne({code:String(input.couponCode).toUpperCase(),active:true});if(c?.perUserLimit!=null)await ensureUserUsage(c._id,userId);}const session=await mongoose.startSession();let created:any;try{await session.withTransaction(async()=>{
 if(idempotencyKey){const prior:any=await Order.findOne({user:userId,idempotencyKey}).session(session);if(prior){if(prior.idempotencyFingerprint&&prior.idempotencyFingerprint!==idempotencyFingerprint)throw fail("Idempotency key was already used for a different checkout request",409);created=prior;return;}}
 const cart:any=await Cart.findOne({user:userId}).session(session);if(!cart?.items?.length)throw fail("Cart is empty");const checkoutOrderId=new mongoose.Types.ObjectId();const settings:any=await SiteSettings.findOne().session(session);const pm:any=await PaymentMethod.findOne({_id:input.paymentMethod,active:true}).session(session);if(!pm)throw fail("Selected payment method is unavailable");
 let subtotal=0;const items:any[]=[];
 for(const ci of cart.items){const qty=Number(ci.quantity);const p:any=await Product.findOne({_id:ci.product,active:true,availability:true}).session(session);if(!p)throw fail("A product is unavailable",409);const v=cartVariant(ci.variant,p);const unit=effectivePrice(p,v);let updated:any;
  const inventoryTx=await adjustInventory(p._id.toString(),-qty,userId,"SALE","Order checkout",v?._id?.toString(),session,"ORDER",checkoutOrderId.toString());
  if(!inventoryTx)throw fail(`Unable to reserve stock for ${p.name}`,409);const line=roundMoney(unit*qty);subtotal=roundMoney(subtotal+line);const commission=commissionSnapshot(p,v,line,qty,settings);items.push({product:p._id,variantId:v?._id,sku:v?.sku||p.sku,productName:p.name,variantName:v?.name,variantAttributes:v?Object.fromEntries(v.attributes||[]):undefined,quantity:qty,unitPrice:unit,discount:0,subtotal:line,image:v?.images?.[0]||p.images?.[0],commission});
 }
 let discount=0,coupon:any;if(input.couponCode){const productIds=items.map(i=>i.product.toString());const cats:any[]=await Product.find({_id:{$in:productIds}}).select("_id category").session(session).lean();const categoryIds=cats.map(x=>x.category?.toString()).filter(Boolean);const current:any=await Coupon.findOne({code:String(input.couponCode).toUpperCase(),active:true}).session(session);const eligibleSubtotal=current&&((current.products?.length||current.categories?.length)?items.reduce((n:number,i:any)=>{const c=cats.find((x:any)=>String(x._id)===String(i.product))?.category?.toString();const eligible=(current.products?.length?current.products.some((x:any)=>String(x)===String(i.product)):false)||(current.categories?.length?current.categories.some((x:any)=>String(x)===String(c)):false);return n+(eligible?Number(i.subtotal):0);},0):subtotal);const valid:any=await validateCoupon(input.couponCode,subtotal,userId,productIds,categoryIds,eligibleSubtotal);coupon=valid.coupon;discount=roundMoney(valid.discount);}
 const shipping=roundMoney(subtotal-discount>=Number(settings?.freeShippingThreshold||5000)?0:Number(settings?.shippingFee||250));const total=roundMoney(subtotal-discount+shipping);
 let aff:any,click:any;if(rawAttribution){try{const payload:any=jwt.verify(rawAttribution,env.JWT_SECRET);click=await AffiliateClick.findOne({_id:payload.clickId,code:payload.code}).session(session);if(click)aff=await Affiliate.findOne({code:payload.code,active:true,user:{$ne:userId}}).populate({path:"user",match:{active:true,affiliateEnabled:true}}).session(session);if(aff&&!aff.user)aff=null;}catch{}}
 created=(await Order.create([{_id:checkoutOrderId,orderNumber:orderNo(),idempotencyKey,idempotencyFingerprint,user:userId,items,subtotal,discount,shipping,total,paymentMethod:pm._id,paymentStatus:"PENDING",status:"PENDING",addressSnapshot:input.address,couponCode:coupon?.code,coupon:coupon?._id,affiliateCode:aff?.code,affiliateUser:aff?.user?._id,affiliateClick:click?._id,statusHistory:[{status:"PENDING",at:new Date(),actor:userId}]}],{session}))[0];
 if(coupon)await reserveUsage(coupon._id,userId,created._id,session);await Cart.updateOne({user:userId},{$set:{items:[]}},{session});await Notification.create([{user:userId,type:"ORDER_PLACED",title:"Order placed",message:`Order ${created.orderNumber} was created.`,data:{orderId:created._id}}],{session});const admins:any[]=await User.find({role:{$in:["admin","super_admin"]},active:true}).select("_id").session(session);if(admins.length)await Notification.create(admins.map(a=>({user:a._id,type:"NEW_ORDER",title:"New order received",message:`New order ${created.orderNumber} requires processing/payment review.`,data:{orderId:created._id}})),{session});
 });return created;}catch(e:any){if(e?.code===11000&&idempotencyKey){const prior:any=await Order.findOne({user:userId,idempotencyKey});if(prior){if(prior.idempotencyFingerprint&&prior.idempotencyFingerprint!==idempotencyFingerprint)throw fail("Idempotency key was already used for a different checkout request",409);return prior;}}throw e;}finally{await session.endSession();}}
export async function previewOrder(userId:string,couponCode?:string){const cart:any=await Cart.findOne({user:userId}).populate("items.product");if(!cart?.items?.length)throw fail("Cart is empty");const settings:any=await SiteSettings.findOne();let subtotal=0;const items:any[]=[];for(const ci of cart.items){const p:any=ci.product;if(!p?.active||!p.availability)throw fail("A product is unavailable",409);const qty=Number(ci.quantity);const v=cartVariant(ci.variant,p);if(v&&v.stock<qty)throw fail(`Insufficient variant stock for ${p.name}`,409);if(!v&&p.stock<qty)throw fail(`Insufficient stock for ${p.name}`,409);const unit=effectivePrice(p,v);const line=roundMoney(unit*qty);subtotal=roundMoney(subtotal+line);items.push({product:p._id,name:p.name,sku:v?.sku||p.sku,quantity:qty,unitPrice:unit,lineTotal:line,variantId:v?._id});}let discount=0,coupon:any;if(couponCode){const productIds=items.map(i=>i.product.toString());const cats:any[]=await Product.find({_id:{$in:items.map(i=>i.product)}}).select("_id category").lean();const current:any=await Coupon.findOne({code:String(couponCode).toUpperCase(),active:true});const eligibleSubtotal=current&&((current.products?.length||current.categories?.length)?items.reduce((n:number,i:any)=>{const c=cats.find((x:any)=>String(x._id)===String(i.product))?.category?.toString();const eligible=(current.products?.length?current.products.some((x:any)=>String(x)===String(i.product)):false)||(current.categories?.length?current.categories.some((x:any)=>String(x)===String(c)):false);return n+(eligible?Number(i.lineTotal):0);},0):subtotal);const valid:any=await validateCoupon(couponCode,subtotal,userId,productIds,cats.map(x=>x.category?.toString()).filter(Boolean),eligibleSubtotal);coupon=valid.coupon;discount=roundMoney(valid.discount);}const shipping=roundMoney(subtotal-discount>=Number(settings?.freeShippingThreshold||5000)?0:Number(settings?.shippingFee||250));return{items,subtotal,discount,shipping,total:roundMoney(subtotal-discount+shipping),coupon:coupon?.code||null};}
