import mongoose from "mongoose";import {Commission,Order,AffiliateConversion,Affiliate,AffiliateClick,CommissionLedger} from "../models";import {commissionReversalDelta,commissionPaymentSettlement} from "../utils/domain";import {record} from "./audit.service";
const fail=(message:string,status=400)=>Object.assign(new Error(message),{status});
const transitions:Record<string,string[]>={PENDING:["APPROVED","REVERSED"],APPROVED:["PAID","REVERSED"],PAID:["REVERSED"],REVERSED:[],REJECTED:[]};
async function ledger(c:any,type:string,amount:number,balanceDelta:number,reason:string,actor?:string,session?:mongoose.ClientSession,metadata?:Record<string,unknown>){await CommissionLedger.create([{affiliate:c.affiliate,commission:c._id,order:c.order,type,amount,balanceDelta,reason,actor,metadata}],{session});}
export async function createCommission(orderId:string,session?:mongoose.ClientSession){return createForOrder(orderId,session)}
export async function createForOrder(orderId:string,session?:mongoose.ClientSession){const o:any=await Order.findById(orderId).session(session||null);if(!o?.affiliateUser||["CANCELLED","REFUNDED"].includes(o.status))return null;const aff:any=await Affiliate.findOne({user:o.affiliateUser,active:true}).session(session||null);if(!aff)return null;const existing=await Commission.findOne({order:o._id}).session(session||null);if(existing)return existing;const items=(o.items||[]).map((i:any)=>({orderItemId:i._id,productId:i.product,variantId:i.variantId,sku:i.sku,quantity:Number(i.quantity),baseAmount:Number(i.subtotal||0),commissionType:i.commission?.type||"percentage",commissionRate:i.commission?.rate,fixedCommissionAmount:i.commission?.fixedCommissionAmount,calculatedAmount:Number(i.commission?.calculatedAmount??0)}));const amount=items.reduce((n:number,i:any)=>n+i.calculatedAmount,0);if(amount<=0)return null;const base=items.reduce((n:number,i:any)=>n+Number(i.baseAmount||0),0);const type=items.every((i:any)=>i.commissionType==="fixed")?"fixed":items.every((i:any)=>i.commissionType==="percentage")?"percentage":"mixed";const commissionRate=type==="percentage"&&base>0?amount/base*100:undefined;const fixedCommissionAmount=type==="fixed"?amount:undefined;let c:any;try{c=(await Commission.create([{affiliate:o.affiliateUser,order:o._id,items,amount,originalAmount:amount,baseAmount:base,commissionRate,fixedCommissionAmount,commissionType:type,status:"PENDING",configSnapshot:items}],{session}))[0]}catch(e:any){if(e?.code===11000)return Commission.findOne({order:o._id}).session(session||null);throw e}await AffiliateConversion.create([{affiliate:o.affiliateUser,order:o._id,click:o.affiliateClick,grossSales:o.total,validSales:0,reversedSales:0,commission:c._id,status:"PENDING",eligibleAt:new Date()}],{session});await Affiliate.updateOne({user:o.affiliateUser},{$inc:{grossConversions:1,grossSales:o.total,pendingCommission:amount}},{session});if(o.affiliateClick)await AffiliateClick.findByIdAndUpdate(o.affiliateClick,{converted:true},{session});await ledger(c,"COMMISSION_CREATED",amount,0,"Commission created after payment approval",undefined,session,{orderId:o._id.toString()});return c;}
export async function approveCommission(id:string,actor?:string){return transition(id,"APPROVED",undefined,actor)}
export async function payCommission(id:string,actor?:string){return transition(id,"PAID",undefined,actor)}
export async function reverseCommission(orderId:string,reason:string,actor?:string,session?:mongoose.ClientSession){const own=!session;const s=session||await mongoose.startSession();let result:any;try{const work=async()=>{const c:any=await Commission.findOne({order:orderId}).session(s);if(!c)return null;if(c.status==="REVERSED")return c;if(!["PENDING","APPROVED","PAID"].includes(c.status))return null;const from=c.status;const amount=Number(c.amount||0);const a:any=await Affiliate.findOne({user:c.affiliate}).session(s);if(!a)throw fail("Affiliate account missing",409);const o:any=await Order.findById(orderId).session(s);const now=new Date();c.status="REVERSED";c.reversalAmount=amount;c.reversedAt=now;c.reason=reason;await c.save({session:s});const delta:any={...commissionReversalDelta(from,amount),reversedConversions:1,reversedSales:Number(o?.total||0)};
if(from==="APPROVED"||from==="PAID"){delta.validConversions=-1;delta.validSales=-Number(o?.total||0);}await Affiliate.updateOne({user:c.affiliate},{$inc:delta},{session:s});await AffiliateConversion.updateOne({order:orderId},{$set:{status:"REVERSED",reversedSales:Number(o?.total||0),validSales:0}},{session:s});await ledger(c,"COMMISSION_REVERSED",amount,Number(delta.availableBalance||0),reason,actor,s,{from});if(from==="PAID")await ledger(c,"COMMISSION_ADJUSTED",amount,0,`Recovery due for paid commission reversal: ${reason}`,actor,s,{source:"PAID_REVERSAL",recoveryDue:amount});await record(actor||"system","COMMISSION_REVERSED","Commission",c._id.toString(),{orderId,from,amount,reason},undefined,s);result=c;};if(own)await s.withTransaction(work);else await work();return result}finally{if(own)await s.endSession()}}
export const list=(affiliate?:string)=>Commission.find(affiliate?{affiliate}:{}).populate("order affiliate").sort({createdAt:-1});
export async function transition(id:string,status:string,reason?:string,actor?:string){if(status==="REVERSED"){const c:any=await Commission.findById(id);if(!c)throw fail("Commission not found",404);return reverseCommission(c.order.toString(),reason||"Admin reversal",actor)}const session=await mongoose.startSession();let out:any;try{await session.withTransaction(async()=>{const c:any=await Commission.findById(id).session(session);if(!c)throw fail("Commission not found",404);if(!transitions[c.status]?.includes(status))throw fail(`Invalid commission transition ${c.status} -> ${status}`,409);const from=c.status;c.status=status;c.reason=reason;if(status==="APPROVED")c.approvedAt=new Date();if(status==="PAID")c.paidAt=new Date();out=await c.save({session});const delta:any={};if(from==="PENDING")delta.pendingCommission=-c.amount;if(status==="APPROVED"){delta.approvedCommission=c.amount;delta.availableBalance=c.amount;await AffiliateConversion.updateOne({order:c.order},{$set:{status:"APPROVED",validSales:Number((await Order.findById(c.order).session(session))?.total||0)}},{session});}if(status==="PAID"){
  delta.approvedCommission=-c.amount;
  // grossPaid/paidCommission are cumulative nominal commission amounts marked PAID.
  // A prior paid reversal creates a recovery obligation which is settled first from
  // the newly payable commission. The affiliate therefore receives only the net cash.
  const affiliate:any=await Affiliate.findOne({user:c.affiliate}).session(session);
  if(!affiliate)throw fail("Affiliate account missing",409);
  const settlement=commissionPaymentSettlement(Number(c.amount||0),Number(affiliate.recoveryDue||0));
  delta.paidCommission=settlement.paidCommission;
  delta.grossPaid=settlement.grossPaid;
  delta.netPaid=settlement.netPaid;
  delta.recoveryDue=settlement.recoveryDue;
  // The approved amount is already in availableBalance. Consume the full nominal
  // amount: recovery settles the outstanding obligation and only the cash remainder
  // is actually transferred to the affiliate.
  delta.availableBalance=settlement.availableBalance;
  delta.reversedAmount=0;
  await ledger(c,"COMMISSION_PAID",settlement.cashPaid,Number(delta.availableBalance||0),reason||`Commission paid (${settlement.cashPaid} cash, ${settlement.recoverySettled} recovery settled)`,actor,session,{from,recoverySettled:settlement.recoverySettled,cashPaid:settlement.cashPaid,nominalAmount:settlement.nominalAmount});
  if(settlement.recoverySettled>0)await ledger(c,"COMMISSION_RECOVERY_SETTLED",settlement.recoverySettled,0,"Paid commission recovery offset",actor,session,{recoverySettled:settlement.recoverySettled});
  await Affiliate.updateOne({user:c.affiliate},{$inc:delta},{session});
  await record(actor||"system","COMMISSION_PAID","Commission",c._id.toString(),{from,to:status,reason,recoverySettled:settlement.recoverySettled,cashPaid:settlement.cashPaid},undefined,session);
  return out;
}await Affiliate.updateOne({user:c.affiliate},{$inc:delta},{session});await ledger(c,status==="APPROVED"?"COMMISSION_APPROVED":"COMMISSION_PAID",c.amount,Number(delta.availableBalance||0),reason||`Commission ${status.toLowerCase()}`,actor,session,{from});await record(actor||"system","COMMISSION_"+status,"Commission",c._id.toString(),{from,to:status,reason},undefined,session)});return out}finally{await session.endSession()}}
