import mongoose from "mongoose";import{Delivery,Order,Notification,Payment,PaymentMethod,Upload}from"../models";import{record}from"./audit.service";
const fail=(m:string,s=400)=>Object.assign(new Error(m),{status:s});
const transitions:Record<string,string[]>={PENDING:["PACKED","SHIPPED","FAILED"],PACKED:["SHIPPED","FAILED"],SHIPPED:["IN_TRANSIT","FAILED","RETURNED"],IN_TRANSIT:["OUT_FOR_DELIVERY","FAILED","RETURNED"],OUT_FOR_DELIVERY:["DELIVERED","FAILED"],DELIVERED:["RETURNED"],FAILED:["RETURNED"],RETURNED:[]};
const orderMap:Record<string,string>={PACKED:"PACKED",SHIPPED:"SHIPPED",IN_TRANSIT:"IN_TRANSIT",OUT_FOR_DELIVERY:"IN_TRANSIT",DELIVERED:"DELIVERED",RETURNED:"CANCELLED"};
export async function get(order:string,user?:string,role?:string){const o:any=await Order.findOne({_id:order,...(role&&["admin","super_admin"].includes(role)?{}:{user})});if(!o)return null;return Delivery.findOne({order}).populate("order proofUpload signatureUpload");}
export async function upsert(order:string,d:any,actor?:string){const s=await mongoose.startSession();let out:any;try{await s.withTransaction(async()=>{const o:any=await Order.findById(order).session(s);if(!o)throw fail("Order not found",404);let del:any=await Delivery.findOne({order}).session(s);
 if(d.proofFileId){const u:any=await Upload.findOne({_id:d.proofFileId,kind:"DELIVERY_PROOF",resourceId:o._id}).session(s);if(!u)throw fail("Invalid delivery proof upload",403);}
 if(d.signatureFileId){const u:any=await Upload.findOne({_id:d.signatureFileId,kind:"DELIVERY_SIGNATURE",resourceId:o._id}).session(s);if(!u)throw fail("Invalid recipient signature upload",403);}const next=d.status||del?.status||"PENDING";if(del&&next!==del.status&&!transitions[del.status]?.includes(next))throw fail(`Invalid delivery transition ${del.status} -> ${next}`,409);
 if(next==="RETURNED"){const payment:any=await Payment.findOne({order:o._id}).session(s);if(!["CANCELLED","REFUNDED"].includes(o.status))throw fail("Returned delivery requires the order to be cancelled or refunded first",409);if(o.status==="REFUNDED"&&payment?.status!=="REFUNDED")throw fail("Returned refunded order must have a refunded payment",409);}const statusChanged=!del || next!==del.status; if(!del){del=new Delivery({order,status:next,statusHistory:[]});}Object.assign(del,{
  status:next, courier:d.courier, trackingNumber:d.trackingNumber, eta:d.eta, deliveryDate:d.deliveryDate,
  recipientName:d.recipientName, recipientConfirmedAt:d.recipientConfirmedAt, notes:d.notes,
  ...(d.proofFileId ? {proofUpload:d.proofFileId,proofUploadedBy:actor,proofUploadedAt:new Date()} : {}),
  ...(d.signatureFileId ? {signatureUpload:d.signatureFileId} : {})
});if(next==="DELIVERED"&&(d.recipientName||d.signatureFileId||d.proofFileId))del.recipientConfirmedAt=d.recipientConfirmedAt||new Date();if(!del.statusHistory)del.statusHistory=[];if(!del.statusHistory.some((h:any)=>h.status===next&&h.at&&Date.now()-new Date(h.at).getTime()<1000)){del.statusHistory.push({status:next,at:new Date(),actor});}await del.save({session:s});if(statusChanged){const pm:any=await PaymentMethod.findById(o.paymentMethod).session(s);const cod=pm?.type==="COD";let mapped=orderMap[next];if(cod){const codMap:any={PACKED:"PROCESSING",SHIPPED:"SHIPPED",IN_TRANSIT:"IN_TRANSIT",OUT_FOR_DELIVERY:"IN_TRANSIT",DELIVERED:"DELIVERED"};mapped=codMap[next]||mapped;}if(mapped&&mapped!==o.status){const allowed:any={PENDING:["PROCESSING"],PAYMENT_APPROVED:["PROCESSING"],PROCESSING:["PACKED","SHIPPED"],PACKED:["SHIPPED"],SHIPPED:["IN_TRANSIT"],IN_TRANSIT:["DELIVERED"],DELIVERED:["COMPLETED"]};if(allowed[o.status]?.includes(mapped)){o.status=mapped;o.statusHistory.push({status:mapped,at:new Date(),actor});await o.save({session:s});}}}if(statusChanged) await Notification.create([{user:o.user,type:"DELIVERY_UPDATE",title:"Delivery updated",message:`Delivery for ${o.orderNumber} is now ${next.replaceAll("_"," ").toLowerCase()}.`,data:{orderId:o._id,status:next}}],{session:s});await record(actor||"system","DELIVERY_STATUS","Delivery",del._id.toString(),{orderId:o._id.toString(),status:next},undefined,s);out=del;});return out}finally{await s.endSession();}}
export const list=()=>Delivery.find().populate("order proofUpload signatureUpload").sort({createdAt:-1});
