import mongoose from 'mongoose';import {Product,InventoryTransaction,User,Notification} from '../models';import {record} from './audit.service';
const fail=(m:string,s=400)=>Object.assign(new Error(m),{status:s});
export const INVENTORY_REASONS=['INITIAL_STOCK','SALE','ORDER_CANCELLATION','CUSTOMER_REFUND','RETURN','MANUAL_ADJUSTMENT','DAMAGED','LOST','RESTOCK','CORRECTION'] as const;
type InventoryReason=typeof INVENTORY_REASONS[number];
export async function adjust(productId:string,change:number,actor?:string,type:InventoryReason='MANUAL_ADJUSTMENT',note='',variantId?:string,session?:mongoose.ClientSession,referenceType?:string,referenceId?:string){
 if(!Number.isInteger(change)||change===0)throw fail('Inventory change must be a non-zero integer'); const own=!session;const s=session||await mongoose.startSession();let out:any;
 try{const work=async()=>{const filter:any={_id:productId};if(variantId){filter['variants._id']=variantId;if(change<0)filter.variants={$elemMatch:{_id:variantId,stock:{$gte:-change}}};}else if(change<0)filter.stock={$gte:-change};const update:any=variantId?{$inc:{'variants.$.stock':change}}:{$inc:{stock:change}};const p:any=await Product.findOneAndUpdate(filter,update,{new:true,session:s});if(!p)throw fail('Insufficient stock or invalid variant',409);const v=variantId?p.variants.id(variantId):null;const balanceAfter=variantId?v?.stock:p.stock;const sku=variantId?v?.sku:p.sku;const tx:any=(await InventoryTransaction.create([{product:productId,variantId,sku,change,balanceAfter,type,referenceType,referenceId,orderId:referenceType==='ORDER'?referenceId:undefined,actor,note}],{session:s}))[0];await record(actor||'system','INVENTORY_ADJUST','InventoryTransaction',tx._id.toString(),{productId,variantId,change,type,note,balanceAfter},undefined,s);out=tx;const balance=Number(balanceAfter||0);if(balance===0||balance<=5){const admins:any[]=await User.find({role:{$in:["admin","super_admin"]},active:true}).select("_id").session(s);if(admins.length)await Notification.create(admins.map(a=>({user:a._id,type:balance===0?"OUT_OF_STOCK":"LOW_STOCK",title:balance===0?"Product out of stock":"Low stock alert",message:`${p.name} ${variantId?`(${sku}) `:""}has ${balance} unit${balance===1?"":"s"} remaining.`,data:{productId:p._id,variantId,balanceAfter:balance}})),{session:s});}};if(own)await s.withTransaction(work);else await work();return out;}finally{if(own)await s.endSession();}}
export async function restore(productId:string,quantity:number,actor:string,type:'ORDER_CANCELLATION'|'CUSTOMER_REFUND'|'RETURN',referenceType:string,referenceId:string,variantId?:string,sku?:string,note='',session?:mongoose.ClientSession){const own=!session;const s=session||await mongoose.startSession();try{let out:any;const work=async()=>{const existing=await InventoryTransaction.findOne({referenceType,referenceId,type,product:productId,variantId:variantId||null}).session(s);if(existing){out=existing;return;}const filter:any={_id:productId};if(variantId)filter['variants._id']=variantId;const update:any=variantId?{$inc:{'variants.$.stock':quantity}}:{$inc:{stock:quantity}};const p:any=await Product.findOneAndUpdate(filter,update,{new:true,session:s});if(!p)throw fail('Product/variant missing during inventory restoration',409);const v=variantId?p.variants.id(variantId):null;out=(await InventoryTransaction.create([{product:productId,variantId,sku:sku||v?.sku||p.sku,change:quantity,balanceAfter:variantId?v.stock:p.stock,type,referenceType,referenceId,orderId:referenceType==='ORDER'?referenceId:undefined,actor,note}],{session:s}))[0];};if(own)await s.withTransaction(work);else await work();return out}finally{if(own)await s.endSession()}}
export const history=(product?:string)=>InventoryTransaction.find(product?{product}:{}).sort({createdAt:-1}).limit(200).populate('product');
